before_install:
- sudo apt-get install -qq libarchive-dev tidy
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.travis.yml config/database.yml
- git --git-dir=spec/fixtures/repository.git init --bare
addons:
  postgresql: '9.3'
services:
- redis
- elasticsearch
language: ruby
rvm:
- 1.9.3
- 2.0.0
env: 
  - TESTFOLDER=spec/models
  - TESTFOLDER=spec/controllers
  - TESTFOLDER=spec/lib
  - TESTFOLDER=spec/workers
  - TESTFOLDER=spec/mailers
script: 
  - bundle exec rake db:test:prepare
  - bundle exec rspec $TESTFOLDER