---
version: '3'
services:
  postgresql:
    image: postgres:9.4
    volumes:
    - ./../pg_data:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=shuttle
    - POSTGRES_PASSWORD=
    - POSTGRES_DB=shuttle_development
    ports:
    - '5432:5432'

  redis:
    image: redis

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    volumes:
    - es_data:/usr/share/elasticsearch/data
    ports:
    - '9200:9200'
    environment:
    - xpack.security.enabled=false

  web:
    build: .
    command: bundle exec rails server -e _env:RAILS_ENV -p 3000 -b 0.0.0.0
    ports:
    - '3000:3000'
    links: &links
    - postgresql:postgresql.shuttle.local
    - redis:redis.shuttle.local
    - elasticsearch:elasticsearch.shuttle.local
    - mailcatcher:mail.shuttle.local
    environment: &environment
    - RAILS_ENV=development
    - RACK_ENV=development
    - SHUTTLE_DB_HOST=postgresql.shuttle.local
    - SHUTTLE_REDIS_HOST=redis.shuttle.local
    - 'SHUTTLE_ES_URL=elasticsearch.shuttle.local:9200'
    - SHUTTLE_MAIL_HOST=mail.shuttle.local
    volumes:
    - .:/app

  worker:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    links: *links
    environment: *environment

  mailcatcher:
    image: schickling/mailcatcher
    ports:
    - '1025:1025'
    - '1080:1080'

volumes:
  postgres_data:
  es_data:
