FROM ruby:2.2.4-slim

RUN mkdir /app
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    git \
    libarchive-dev \
    libpq-dev \
    make \
    nodejs \
    postgresql-client \
    tidy \
    && rm -rf /var/lib/apt/lists/*

COPY Gemfile Gemfile.lock ./
RUN bundle install --jobs 4 --retry 5 --without development test

COPY . ./

CMD bundle exec rails server
