module Importer

  # Parses translatable strings from Apple Xib files (versions 3 and above),
  # generated by Xcode 5 and up.

  class Xib3 < Storyboard
    include IosCommon

    # Xpaths of strings to extract.
    XPATHS                      = [
        "//accessibility",
        "//label",
        "//segments",
        "//state[@key = 'disabled']",
        "//state[@key = 'highlighted']",
        "//state[@key = 'normal']",
        "//state[@key = 'selected']",
        "//textField"
    ]

    protected

    def import_file?(locale=nil)
      file.path =~ /#{Regexp.escape(locale_to_use(locale).rfc5646)}\.lproj\/[^\/]+\.xib$/
    end

    def import_strings(receiver)
      xml = Nokogiri::XML(file.contents)
      return unless xml.root.name == 'document'

      super #TODO calls Nokogiri:XML twice
    end
  end
end
