language: ruby
ruby:
 - ruby-2.0.0-p353
targets:
- type: specs
  glob: spec/**/*_spec.rb
  workers: 8
  queue_override: linux
- type: jasmine
  glob: "spec/**/*.{js,coffee}"
  workers: 1
  queue_override: linux
