#!/usr/bin/env bash

source "$HOME/.rvm/scripts/rvm"
export LC_CTYPE=en_US.UTF-8
export LANG=en_US.UTF-8
RUN_LIST=$(echo ${RUN_LIST} | tr "," " ")

ensure_dependency() {
  if hash apt-get 2>/dev/null; then
    sudo apt-get install $1
  elif hash yum 2>/dev/null; then
    sudo yum install $1
  elif hash brew 2>/dev/null; then
    brew install $1
  fi
}

ensure_phantomjs() {
  if hash apt-get 2>/dev/null; then
    sudo apt-get install build-essential chrpath git-core libssl-dev libfontconfig1-dev
    git clone git://github.com/ariya/phantomjs.git
    cd phantomjs
    git checkout 1.9
    ./build.sh --confirm
  elif hash yum 2>/dev/null; then
    sudo yum install gcc gcc-c++ make git openssl-devel freetype-devel fontconfig-devel
    git clone git://github.com/ariya/phantomjs.git
    cd phantomjs
    git checkout 1.9
    ./build.sh --confirm
  elif hash brew 2>/dev/null; then
    brew install phantomjs
  fi
}

function install_bundler_if_needed() {
  echo "Checking for Bundler ${bundler_version}..."
  if gem list --installed bundler>/dev/null; then
    gem update bundler
  else
    gem install bundler
  fi
}

function update_gems_if_needed() {
  echo "Installing gems..."
  bin/bundle
}

function prepare_database() {
  dropdb -h 127.0.0.1 shuttle_test || true
  dropuser -h 127.0.0.1 shuttle || true
  createuser -D -R -S -h 127.0.0.1 shuttle || true
  createdb -h 127.0.0.1 -O shuttle shuttle_test
  psql -h 127.0.0.1 -U shuttle -f db/structure.sql shuttle_test
}

function run_specs() {
  bin/bundle exec rspec ${RUN_LIST}
}

function run_jasmine() {
  bin/bundle exec rake guard:jasmine -t
}

function prepare() {
  ensure_phantomjs &&
  ensure_dependency "libarchive" &&
  ensure_dependency "qt" &&
  install_bundler_if_needed &&
  update_gems_if_needed &&
  prepare_database
}

prepare

case "${TEST_RUNNER}" in
  jasmine)
    run_jasmine
  ;;

  specs)
    run_specs
  ;;
  *)
    echo "unknown test runner: ${TEST_RUNNER}"
    exit 127
  ;;
esac
