# Copyright 2014 Square Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

require 'localizer/storyboard'
require 'localizer/copies_ios_resources_without_translations'
require 'importer/xib3'

module Localizer

  # Applies localized copy to Xib files generated by Xcode 5 or newer.

  class Xib3 < Storyboard
    def self.localizable?(project, key)
      key.source =~ /#{Regexp.escape project.base_rfc5646_locale}\.lproj\/[^\/]+\.xib$/ &&
          key.importer == 'xib3'
    end

    private

    include CopiesIosResourcesWithoutTranslations
    def copy_resource?(path, blob, project)
      throw :prune if project.skip_path?(::File.dirname(path), Importer::Xib3)
      path =~ /#{Regexp.escape(project.base_rfc5646_locale)}\.lproj\/[^\/]+\.xib$/ &&
          Nokogiri::XML(blob.contents).root.name == 'document'
    end
  end
end
